version: '3.4'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: passw@rd
      AUTH_USER_PWD: autPassw@ord
      AUTH_DB: auth
      AUTH_USER: auth_user
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "auth" ]
      interval: 30s
      timeout: 60s
      retries: 5

  testdb:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: passw@rd
      AUTH_USER_PWD: autPassw@ord
      AUTH_DB: auth
      AUTH_USER: auth_user

  authservice:
    depends_on:
      db:
        condition: service_healthy
    build: .

    environment:
      DATABASE_HOST: db
      DATABASE_TYPE: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: auth_user
      DATABASE_PASSWORD: autPassw@ord
      DATABASE_DBNAME: auth
      DATABASE_SSLMODE: disable
      GRPCPORT: 50052
      TLSCONFIG_USETLS: 'false'
    ports:
      - '50052:50052'