version: '3.4'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: passw@rd
      AUTH_USER_PWD: autPassw@ord
      AUTH_DB: auth
      AUTH_USER: auth_user

  authservice:
    depends_on:
      db:
        condition: service_started
    build: .

    environment:
      DATABASE_HOST: db
      GRPCPORT: 50052
      TLSCONFIG_USETLS: 'false'
    ports:
      - '50052:50052'