// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package pg

import ()

type User struct {
	ID           int64
	Username     string
	PasswordHash string
}

type Version struct {
	Version string
}
