network: "tcp"
address: ""
gRPCPort: 50051
TLSConfig:
  useTLS: true
  certFile: "cert/server_cert.pem"
  keyFile: "cert/server_key.pem"
  CAFile: ""
  serverAddress: "127.0.0.1"
database:
  host: "localhost"
  port: 5432
  userName: "auth_user"
  password: "autPassw@ord"
  dbName: "auth"
password:
  minLength: 4
  minNumeric: 0
  minUpperCase: 0
  minLowerCase: 0
  minSpecial: 0
token:
  signingMethod: "HS256"
  signedKey: "fksdljfkljsd;akfjlfsdkfjsdkla"
  audience: "audience_test"
  issuer: "authservice.yannd.dev"
  expDuration: 5