#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $AUTH_USER WITH PASSWORD '$AUTH_USER_PWD';
	CREATE DATABASE $AUTH_DB;
	GRANT ALL PRIVILEGES ON DATABASE $AUTH_DB TO $AUTH_USER;
	ALTER DATABASE  $AUTH_DB OWNER TO $AUTH_USER;
EOSQL
